import { Difficulty, ExerciseType } from './types';

export const EXERCISE_TYPE_OPTIONS: { value: ExerciseType; label: string }[] =
  Object.values(ExerciseType).map((value) => ({
    value,
    label: value,
  }));

export const DIFFICULTY_OPTIONS: { value: Difficulty; label: string }[] =
  Object.values(Difficulty).map((value) => ({
    value,
    label: value,
  }));

export const TOPICS_BY_DIFFICULTY: {
  [key in Difficulty]: { [category: string]: string[] };
} = {
  [Difficulty.A1]: {
    Vocabulario: [
      'Saludos y despedidas (Unidad 0, 1)',
      'El alfabeto y los números (Unidad 0, 1)',
      'Objetos de la clase y frases útiles (Unidad 0)',
      'Información personal (nombre, edad, etc.) (Unidad 1)',
      'Nacionalidades y profesiones (Unidad 1)',
      'Idiomas y motivaciones para aprender (Unidad 2)',
      'Actividades de ocio y aficiones (Unidad 2)',
      'Describir lugares (ciudades, países) (Unidad 3, 8)',
      'El tiempo y las estaciones del año (Unidad 3)',
      'La ropa, los colores y las compras (Unidad 4)',
      'La familia y las relaciones personales (Unidad 5)',
      'Descripción física y de carácter (Unidad 5)',
      'La rutina diaria y los hábitos (Unidad 6)',
      'La hora y los días de la semana (Unidad 6)',
      'La comida, alimentos y bebidas (Unidad 7)',
      'En el restaurante y el bar (Unidad 7)',
      'El barrio, la ciudad y las tiendas (Unidad 8)',
      'Habilidades y capacidades (Unidad 9)',
    ],
    Gramática: [
      'Verbos ser, tener y llamarse (Unidad 1)',
      'Pronombres personales de sujeto (Unidad 1)',
      'El género y el número (Unidad 1, 2)',
      'Artículos determinados e indeterminados (Unidad 2)',
      'Presente de indicativo (verbos regulares) (Unidad 2)',
      'Usos de por, para y porque (Unidad 2)',
      'Verbos hay y estar (existencia y ubicación) (Unidad 3)',
      'Interrogativos (qué, cuál, dónde, etc.) (Unidad 3)',
      'Los demostrativos (este, ese, aquel) (Unidad 4)',
      'Tener que + infinitivo (Unidad 4)',
      'Verbo gustar y expresar gustos (Unidad 5, 8)',
      'Los posesivos (Unidad 5)',
      'Presente de indicativo (verbos irregulares) (Unidad 6)',
      'Verbos pronominales (reflexivos) (Unidad 6)',
      'Adverbios de frecuencia (Unidad 6)',
      'Pronombres de Objeto Directo (lo, la, los, las) (Unidad 7)',
      'Preposiciones y adverbios de lugar (Unidad 8)',
      'Pretérito perfecto (experiencias pasadas) (Unidad 9)',
      'Saber y poder + infinitivo (Unidad 9)',
    ],
  },
  [Difficulty.A2]: {
    Vocabulario: [
      'Sentimientos y estados de ánimo (Unidad 1, 8, 10)',
      'Actividades y consejos para aprender un idioma (Unidad 1)',
      'Biografías, logros y acontecimientos históricos (Unidad 2)',
      'Cine y películas (Unidad 2)',
      'Descripción física y de carácter (aspecto, personalidad) (Unidad 3)',
      'Relaciones personales y de pareja (llevarse bien/mal) (Unidad 3)',
      'La vivienda: tipos, partes y muebles (Unidad 4)',
      'Describir y comparar objetos (formas, estilos, materiales) (Unidad 4)',
      'Fórmulas de cortesía (pedir favores, disculparse) (Unidad 5)',
      'Saludos y despedidas formales e informales (Unidad 5)',
      'Actividades de ocio, cultura y tiempo libre (Unidad 6)',
      'Lugares de interés en una ciudad (Unidad 6)',
      'Alimentos, recetas y hábitos alimentarios (Unidad 7)',
      'Pesos y medidas (Unidad 7)',
      'El cuerpo humano y la salud (Unidad 8)',
      'Dolores, enfermedades y síntomas (Unidad 8)',
      'Etapas de la vida e historia personal (Unidad 2, 9)',
      'Cambios y costumbres (antes y ahora) (Unidad 9)',
      'Anécdotas, recuerdos y emociones (Unidad 10)',
    ],
    Gramática: [
      'Presente de indicativo (repaso de regulares e irregulares) (Unidad 1, 3)',
      'Verbos reflexivos (sentirse, llevarse, etc.) (Unidad 1, 3)',
      'Verbos como "costar" y "parecerse" (Unidad 1, 3)',
      'Pretérito indefinido (regulares e irregulares) (Unidad 2, 6)',
      'Contraste entre pretérito indefinido y pretérito imperfecto (Unidad 10)',
      'Marcadores temporales de pasado (Unidad 2, 9, 10)',
      'Pretérito imperfecto (descripciones, hábitos en el pasado) (Unidad 9)',
      'Pretérito perfecto (experiencias de vida) (Unidad 6)',
      'Usos de "ya" y "todavía no" (Unidad 6)',
      'Comparativos y superlativos (Unidad 4)',
      'Pronombres posesivos (el mío, el tuyo, etc.) (Unidad 4)',
      'Preposiciones y adverbios de lugar (Unidad 4)',
      'Estar + gerundio (acciones en desarrollo en presente y pasado) (Unidad 5, 10)',
      'El condicional para expresar cortesía (podría, me gustaría) (Unidad 5)',
      'Pronombres de Objeto Directo (repaso) (Unidad 7)',
      'Usos de "se" (impersonal, no se puede, etc.) (Unidad 7)',
      'Verbo "soler" + infinitivo (Unidad 7)',
      'Verbo "doler" (Unidad 8)',
      'Imperativo afirmativo (dar consejos) (Unidad 8)',
      'Conectores (desde, hasta, durante...) (Unidad 2)',
      'Futuro próximo (ir a + infinitivo) (Unidad 6)',
      'Querer / Pensar + infinitivo (expresar intenciones) (Unidad 6)',
    ],
  },
  [Difficulty.B1]: {
    Vocabulario: [
      'Costumbres sociales y normas (Unidad 1)',
      'El ámbito laboral y profesional (Unidad 1, 2)',
      'El futuro, la tecnología y la ciencia (Unidad 3, 12)',
      'Cine, televisión y literatura (Unidad 4)',
      'Publicidad y consumo (Unidad 5)',
      'Activismo y problemas sociales (Unidad 6, 11)',
      'Tipos de mensajes y comunicación (Unidad 7)',
      'Viajes, turismo y anécdotas (Unidad 8)',
      'Intereses, sentimientos y relaciones (Unidad 9)',
      'Descripción de objetos (diseño, forma, material) (Unidad 10)',
      'Acciones para un mundo mejor (Unidad 11)',
      'Misterios y fenómenos paranormales (Unidad 12)',
    ],
    Gramática: [
      'Expresar impersonalidad (se prohíbe, está permitido, lo normal es...) (Unidad 1)',
      'Perífrasis verbales (soler, empezar a, dejar de, llevar + gerundio) (Unidad 1, 2)',
      'Futuro simple para predicciones e hipótesis (Unidad 3, 12)',
      'Oraciones condicionales (si + presente, futuro) (Unidad 3)',
      'Conectores discursivos (causa, consecuencia, contraste) (Unidad 4, 8)',
      'Pronombres de Objeto Directo e Indirecto (Unidad 4)',
      'Imperativo afirmativo y negativo (Unidad 5)',
      'Colocación de pronombres con el imperativo (Unidad 5)',
      'Presente de subjuntivo para expresar deseos y necesidad (Unidad 6)',
      'Presente de subjuntivo para expresar opiniones y valoraciones (Unidad 11)',
      'Estilo indirecto en presente (decir/pedir/preguntar que...) (Unidad 7)',
      'Contraste de los tiempos del pasado (perfecto, indefinido, imperfecto) (Unidad 8)',
      'Pretérito pluscuamperfecto de indicativo (Unidad 8)',
      'Verbos de sentimiento + que + subjuntivo (me encanta que...) (Unidad 9)',
      'Superlativos absolutos (-ísimo) y frases exclamativas (Unidad 10)',
      'Oraciones de relativo con indicativo y subjuntivo (Unidad 10)',
      'Condicional simple para aconsejar y proponer (Unidad 11)',
      'Futuro compuesto para hacer suposiciones sobre el pasado (Unidad 12)',
    ],
  },
  [Difficulty.B2]: {
    Vocabulario: [
        'El cuerpo, la postura y los movimientos (Libro 4, Unidad 1)',
        'Sentimientos, actitudes y estados de ánimo (Libro 4, U1, U5; Libro 5, U3, U4)',
        'Conflictos y mediación (Libro 4, Unidad 2)',
        'Relatos, cuentos y leyendas (Libro 4, Unidad 3)',
        'Catástrofes y fenómenos naturales (Libro 4, Unidad 3)',
        'Historia, personajes y acontecimientos (Libro 4, Unidad 3, 6)',
        'Medioambiente y concienciación social (Libro 4, Unidad 4)',
        'El ámbito laboral (cualidades, funciones, problemas) (Libro 4, Unidad 5)',
        'Educación y recorridos vitales (Libro 4, U6; Libro 5, U6)',
        'Medios de comunicación y noticias (Libro 5, Unidad 1)',
        'Leyes, burocracia y gestión (Libro 5, Unidad 2)',
        'Deportes, tradiciones, miedos y fobias (Libro 5, Unidad 3)',
        'Relaciones personales y afectivas (Libro 5, Unidad 4)',
        'Tribus urbanas (Libro 5, Unidad 4)',
        'Descripción de ciudades y viajes (Libro 5, Unidad 5)',
        'Concursos, convocatorias y requisitos (Libro 5, Unidad 6)',
    ],
    Gramática: [
        'Describir acciones (adjetivos, gerundios, adverbios) (Libro 4, Unidad 1)',
        'Verbos pronominales (quedar/quedarse, sentir/sentirse) (Libro 4, Unidad 1)',
        'Expresar finalidad: para + infinitivo / para que + subjuntivo (Libro 4, Unidad 2)',
        'Estilo indirecto: aludir a promesas (Libro 4, Unidad 2)',
        'Usos de "se" para expresar involuntariedad (Libro 4, Unidad 2)',
        'Combinar tiempos del pasado en la narración (Libro 4, Unidad 3)',
        'Marcadores temporales: justo cuando, entonces... (Libro 4, Unidad 3)',
        'Usos del pretérito imperfecto de subjuntivo (Libro 4, U3; Libro 5, U3)',
        'El futuro compuesto (Libro 4, Unidad 4)',
        'Construcciones temporales: mientras, hasta que, en cuanto... (Libro 4, Unidad 4)',
        'Oraciones concesivas: aunque, a pesar de, por mucho que... (Libro 4, Unidad 5)',
        'Reformular y ejemplificar (Libro 4, Unidad 5)',
        'Combinaciones de pronombres de objeto (Libro 4, Unidad 6)',
        'El pretérito pluscuamperfecto de subjuntivo (Libro 4, Unidad 6)',
        'El condicional compuesto (Libro 4, Unidad 6)',
        'Conectores de causa y consecuencia (Libro 4, Unidad 6)',
        'La voz pasiva y las construcciones impersonales con "se" (Libro 5, Unidad 1, 6)',
        'Uso de la 3ª persona del plural con valor impersonal (Libro 5, Unidad 1)',
        'Expresar opinión: (no) creo/pienso que + indicativo/subjuntivo (Libro 5, Unidad 2)',
        'Expresar condiciones: solo si, siempre que... (Libro 5, Unidad 2)',
        'Usos del condicional simple para dar consejos (Libro 5, Unidad 3)',
        'Correlación de tiempos verbales en frases de relativo (Libro 5, Unidad 4)',
        'Conectores para añadir, matizar y contraponer información (Libro 5, Unidad 4)',
        'Oraciones de relativo: que, quien/es, cuyo/a/os/as (Libro 5, Unidad 5)',
        'Verbos de percepción y opinión + indicativo / subjuntivo (Libro 5, Unidad 5)',
        'Usos del infinitivo compuesto (Libro 5, Unidad 6)',
        'El pretérito perfecto de subjuntivo (Libro 5, Unidad 6)',
    ],
  },
  [Difficulty.C1]: {
    Vocabulario: [
      'La carrera profesional y el aprendizaje (Aprendizaje)',
      'Sentido figurado y colocaciones (florecer, sacar provecho) (Aprendizaje)',
      'El sistema educativo, estudios y titulaciones (Aprendizaje)',
      'Contratación de servicios y atención al cliente (Consumo)',
      'El arte, las exposiciones y los sentidos (Arte)',
      'Expresiones de registro coloquial y argot (Arte)',
      'La información, los datos y los medios de comunicación (Datos)',
      'Discursos, debate y lenguaje político (Discurso)',
      'Las emociones, los deportes y la superación (Emociones)',
      'Estereotipos y relaciones interpersonales (Fronteras)',
      'Carácter y personalidad (Fronteras, Identidad)',
      'Hábitos, horarios, ocio y tiempo libre (Horarios)',
      'La identidad personal y la imagen pública (Identidad)',
      'Comportamientos sexistas y (des)igualdad de género (Mujeres)',
      'La memoria, la infancia y la historia (Memoria)',
      'El cine, la historia y las celebraciones familiares (Memoria)',
      'La naturaleza, el paisaje y el medioambiente (Naturaleza)',
      'Los orígenes, los rasgos físicos y el ambiente de un lugar (Orígenes)',
      'Las redes sociales y las relaciones personales en línea (Red)',
      'La seducción, la persuasión y los influencers (Seducción)',
      'La tecnología, la economía y el trabajo (Tecnología)',
    ],
    Gramática: [
      'Perífrasis de continuidad y cambio (seguir + gerundio, dejar de + infinitivo) (Aprendizaje)',
      'Recursos para comparar (mientras que, más/menos de) (Aprendizaje)',
      'Oraciones y conectores condicionales (salvo que, siempre y cuando) (Consumo)',
      'El adverbio "siquiera" y el "si" independiente (Consumo)',
      'Finalidad (para + infinitivo, para que + subjuntivo) (Datos)',
      'El participio presente (concerniente, perteneciente) (Datos)',
      'Expresar arrepentimiento y lamento (infinitivo simple/compuesto) (Discurso)',
      'Marcadores consecutivos (en consecuencia, por consiguiente) (Discurso)',
      'Uso pronominal de verbos y usos del gerundio (Emociones)',
      'Pronombres reflexivos tónicos (mí, ti, sí...) (Emociones)',
      'Perífrasis verbales de inicio de acción (empezar/ponerse a + inf) (Emociones)',
      'Futuro y condicional para expresar hipótesis (Fronteras)',
      'Correlación temporal en subordinadas (presente/imperfecto de subjuntivo) (Horarios)',
      'Construcciones con "como" + subjuntivo (Horarios)',
      'Adverbios evaluativos terminados en -mente (Identidad)',
      'Perífrasis de desarrollo y progreso (ir/venir/terminar + gerundio) (Mujeres)',
      'Usos de "se" (accidental, etc.) (Memoria, Mujeres)',
      'Construcción "lo" + adjetivo (Memoria)',
      'Usos de por y para (repaso y ampliación) (Naturaleza)',
      'Oraciones y marcadores concesivos (aunque, a pesar de, aun + gerundio) (Naturaleza)',
      'Comparativas proporcionales (cuanto más..., más...) (Orígenes)',
      'Concesivas con "por mucho/más/poco que" + subjuntivo (Orígenes)',
      '"Que" independiente (exclamativo/imperativo) (Red)',
      '"Que" + indicativo/subjuntivo en estructuras de opinión (Red)',
      'Comparaciones con "como si" + imperfecto/pluscuamperfecto de subjuntivo (Seducción)',
      'Oraciones temporales de simultaneidad (según, conforme, a medida que) (Seducción)',
      'Contraste entre "el" y "lo" (Tecnología)',
      'Uso del subjuntivo en lugar de la nominalización (Tecnología)',
    ],
  },
};
